#!/bin/bash
# =============================================================================
# Meshlink Server - Automated Setup Script
# Installs and configures the full Meshlink messaging stack on Ubuntu.
#
# Usage:
#   chmod +x setup.sh && sudo ./setup.sh
#
# What it does:
#   1. Installs Docker and Docker Compose (if missing)
#   2. Generates secure secrets
#   3. Templates all config files with your server parameters
#   4. Starts the full server stack
#   5. Creates the first admin user
# =============================================================================

set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[Meshlink]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# --- Pre-flight checks ---
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (use sudo)."
    exit 1
fi

if ! grep -qi 'ubuntu\|debian' /etc/os-release 2>/dev/null; then
    warn "This script is designed for Ubuntu/Debian. Proceeding anyway..."
fi

# --- Determine script and project directories ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

log "Meshlink server directory: $SERVER_DIR"

# =============================================================================
# Step 1: Collect configuration
# =============================================================================
echo ""
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}   Meshlink Server Setup${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# Detect public IP
DETECTED_IP=$(curl -4 -s --max-time 5 ifconfig.co 2>/dev/null || hostname -I | awk '{print $1}')

read -rp "Server IP or domain [$DETECTED_IP]: " SERVER_HOST
SERVER_HOST="${SERVER_HOST:-$DETECTED_IP}"

HTTP_PORT="80"

read -rp "Admin username [admin]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-admin}"
# Sanitize: only allow a-z, 0-9, underscore, dash, dot
ADMIN_USER=$(echo "$ADMIN_USER" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_.-]//g')
if [ -z "$ADMIN_USER" ]; then
    ADMIN_USER="admin"
fi
log "Admin username: $ADMIN_USER"

while true; do
    read -rsp "Admin password (min 8 chars): " ADMIN_PASSWORD
    echo ""
    if [ "${#ADMIN_PASSWORD}" -ge 8 ]; then
        break
    fi
    warn "Password must be at least 8 characters."
done

# Registration always enabled -- users need to be able to sign up
ENABLE_REGISTRATION="true"

# =============================================================================
# Step 2: Install Docker (if needed)
# =============================================================================
install_docker() {
    if command -v docker &>/dev/null; then
        log "Docker already installed: $(docker --version)"
        return
    fi

    log "Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin

    systemctl enable docker
    systemctl start docker
    log "Docker installed successfully."
}

install_docker

# Ensure docker compose works
if ! docker compose version &>/dev/null; then
    err "docker compose not available. Please install Docker Compose v2."
    exit 1
fi

# =============================================================================
# Step 3: Generate secrets
# =============================================================================
gen_secret() { openssl rand -hex 32; }

POSTGRES_PASSWORD="$(gen_secret)"
REGISTRATION_SHARED_SECRET="$(gen_secret)"
MACAROON_SECRET="$(gen_secret)"
FORM_SECRET="$(gen_secret)"
TURN_SECRET="$(gen_secret)"

log "Secrets generated."

# =============================================================================
# Step 4: Write .env file
# =============================================================================
cat > "$SERVER_DIR/.env" <<EOF
# Meshlink Server Configuration (auto-generated by setup.sh)
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

SERVER_HOST=${SERVER_HOST}
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=443
SYNAPSE_PORT=8008
TURN_PORT=3478
TURN_TLS_PORT=5349
TURN_RELAY_MIN=49152
TURN_RELAY_MAX=49172

SYNAPSE_SERVER_NAME=${SERVER_HOST}
SYNAPSE_REPORT_STATS=no
ENABLE_REGISTRATION=${ENABLE_REGISTRATION}
REGISTRATION_SHARED_SECRET=${REGISTRATION_SHARED_SECRET}

POSTGRES_DB=synapse
POSTGRES_USER=synapse
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

TURN_SECRET=${TURN_SECRET}

ELEMENT_BRAND=Meshlink

ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

chmod 600 "$SERVER_DIR/.env"
log ".env file written."

# =============================================================================
# Step 5: Template config files (using envsubst for reliability)
# =============================================================================

# Export all variables needed by templates
export SERVER_HOST SERVER_NAME="${SERVER_HOST}"
export POSTGRES_USER="synapse" POSTGRES_PASSWORD POSTGRES_DB="synapse"
export ENABLE_REGISTRATION REGISTRATION_SHARED_SECRET
export MACAROON_SECRET FORM_SECRET TURN_SECRET
export TURN_PORT="3478"

TEMPLATE_VARS='${SERVER_HOST} ${SERVER_NAME} ${POSTGRES_USER} ${POSTGRES_PASSWORD} ${POSTGRES_DB} ${ENABLE_REGISTRATION} ${REGISTRATION_SHARED_SECRET} ${MACAROON_SECRET} ${FORM_SECRET} ${TURN_SECRET} ${TURN_PORT}'

template_file() {
    local file="$1"
    log "Templating: $file"
    local tmp="${file}.tmp"
    envsubst "$TEMPLATE_VARS" < "$file" > "$tmp"
    mv "$tmp" "$file"
}

# Copy originals from git before templating (allows re-running setup.sh)
REPO_DIR="$(cd "$SERVER_DIR/.." && pwd)"
if [ -f "$REPO_DIR/.git/HEAD" ]; then
    log "Restoring config templates from git..."
    git -C "$REPO_DIR" checkout -- server/synapse/homeserver.yaml server/coturn/turnserver.conf server/element/config.json 2>/dev/null || true
fi

template_file "$SERVER_DIR/synapse/homeserver.yaml"
template_file "$SERVER_DIR/coturn/turnserver.conf"
template_file "$SERVER_DIR/element/config.json"

log "All config files templated."

# =============================================================================
# Step 6: Generate self-signed TLS certificate and HTTPS nginx config
# =============================================================================
SSL_DIR="$SERVER_DIR/nginx/ssl"
mkdir -p "$SSL_DIR"

log "Generating self-signed TLS certificate..."
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout "$SSL_DIR/meshlink.key" \
    -out "$SSL_DIR/meshlink.crt" \
    -subj "/CN=${SERVER_HOST}/O=Meshlink/C=XX" \
    -addext "subjectAltName=IP:${SERVER_HOST},DNS:${SERVER_HOST}" \
    2>/dev/null
chmod 600 "$SSL_DIR/meshlink.key"
chmod 644 "$SSL_DIR/meshlink.crt"
log "TLS certificate generated."

# Write HTTPS nginx config (replaces the default HTTP-only config from git)
log "Writing HTTPS nginx config..."
cat > "$SERVER_DIR/nginx/conf.d/default.conf" <<'NGINXCONF'
limit_req_zone $binary_remote_addr zone=synapse_login:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=synapse_register:10m rate=3r/s;

server {
    listen 0.0.0.0:80 default_server;
    server_name _;
    location /health { access_log off; return 200 "OK\n"; add_header Content-Type text/plain; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 0.0.0.0:443 ssl default_server;
    server_name _;

    ssl_certificate     /etc/nginx/ssl/meshlink.crt;
    ssl_certificate_key /etc/nginx/ssl/meshlink.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options nosniff always;

    client_max_body_size 50m;

    location / {
        root /usr/share/nginx/www/meshlink;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /element/ { proxy_pass http://element:80/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme; }
    location = /element { return 301 /element/; }

    location /_matrix {
        proxy_pass http://synapse:8008;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 600s;
        proxy_buffering off;
    }

    location /_matrix/media {
        proxy_pass http://synapse:8008;
        proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off; proxy_read_timeout 300s; client_max_body_size 50m;
    }

    location /.well-known/matrix/ { proxy_pass http://synapse:8008; proxy_set_header Host $host; }
    location /_synapse { proxy_pass http://synapse:8008; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
    location /admin/ { proxy_pass http://synapse-admin:80/; proxy_set_header Host $host; }
    location = /admin { return 301 /admin/; }

    location /_matrix/client/v3/login {
        limit_req zone=synapse_login burst=10 nodelay;
        proxy_pass http://synapse:8008;
        proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /_matrix/client/v3/register {
        limit_req zone=synapse_register burst=10 nodelay;
        proxy_pass http://synapse:8008;
        proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /config { proxy_pass http://admin-api:9090/; proxy_set_header Host $host; }
    location /api/ { proxy_pass http://admin-api:9090; proxy_set_header Host $host; }
    location /installers/ { alias /usr/share/nginx/www/installers/; autoindex off; }
    location /health { access_log off; return 200 "OK\n"; add_header Content-Type text/plain; }
}
NGINXCONF
log "HTTPS nginx config written."

# =============================================================================
# Step 6b: Create directories for nginx static files
# =============================================================================
mkdir -p "$SERVER_DIR/nginx/www/installers"
mkdir -p "$SERVER_DIR/nginx/www/meshlink"

# Generate platform installers pointing to this server (HTTPS)
BASE_URL="https://${SERVER_HOST}"
if [ "$HTTP_PORT" != "80" ]; then
    BASE_URL="http://${SERVER_HOST}:${HTTP_PORT}"
fi

# Windows installer
cat > "$SERVER_DIR/nginx/www/installers/Meshlink-Install.bat" <<WINEOF
@echo off
title Meshlink Installer
color 0A
echo.
echo  ========================================
echo     Meshlink - Decentralized Messenger
echo  ========================================
echo.
echo  Installing Meshlink...

set "SERVER_URL=${BASE_URL}"

mkdir "%USERPROFILE%\Meshlink" 2>nul

echo @echo off > "%USERPROFILE%\Meshlink\Meshlink.bat"
echo start "" "%SERVER_URL%" >> "%USERPROFILE%\Meshlink\Meshlink.bat"

echo Set ws = CreateObject("WScript.Shell") > "%TEMP%\ml_sc.vbs"
echo Set sc = ws.CreateShortcut(ws.SpecialFolders("Desktop") ^& "\Meshlink.lnk") >> "%TEMP%\ml_sc.vbs"
echo sc.TargetPath = "%USERPROFILE%\Meshlink\Meshlink.bat" >> "%TEMP%\ml_sc.vbs"
echo sc.IconLocation = "shell32.dll,14" >> "%TEMP%\ml_sc.vbs"
echo sc.Description = "Meshlink Messenger" >> "%TEMP%\ml_sc.vbs"
echo sc.WindowStyle = 7 >> "%TEMP%\ml_sc.vbs"
echo sc.Save >> "%TEMP%\ml_sc.vbs"
cscript //nologo "%TEMP%\ml_sc.vbs"
del "%TEMP%\ml_sc.vbs" 2>nul

mkdir "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Meshlink" 2>nul
echo Set ws = CreateObject("WScript.Shell") > "%TEMP%\ml_sm.vbs"
echo Set sc = ws.CreateShortcut("%APPDATA%\Microsoft\Windows\Start Menu\Programs\Meshlink\Meshlink.lnk") >> "%TEMP%\ml_sm.vbs"
echo sc.TargetPath = "%USERPROFILE%\Meshlink\Meshlink.bat" >> "%TEMP%\ml_sm.vbs"
echo sc.IconLocation = "shell32.dll,14" >> "%TEMP%\ml_sm.vbs"
echo sc.Description = "Meshlink Messenger" >> "%TEMP%\ml_sm.vbs"
echo sc.Save >> "%TEMP%\ml_sm.vbs"
cscript //nologo "%TEMP%\ml_sm.vbs"
del "%TEMP%\ml_sm.vbs" 2>nul

echo.
echo  ========================================
echo   Done! Shortcut created on Desktop.
echo   Opening Meshlink now...
echo  ========================================

start "" "%SERVER_URL%"
exit
WINEOF

# Linux installer
cat > "$SERVER_DIR/nginx/www/installers/meshlink-install.sh" <<LINEOF
#!/bin/bash
# Meshlink Installer for Linux

SERVER_URL="${BASE_URL}"

echo ""
echo "========================================"
echo "   Meshlink - Decentralized Messenger"
echo "========================================"
echo ""
echo "Installing..."

mkdir -p "\$HOME/Meshlink"

cat > "\$HOME/Meshlink/meshlink" << 'LAUNCHER'
#!/bin/bash
xdg-open "${BASE_URL}" 2>/dev/null || sensible-browser "${BASE_URL}" 2>/dev/null || firefox "${BASE_URL}" 2>/dev/null || google-chrome "${BASE_URL}" 2>/dev/null
LAUNCHER
chmod +x "\$HOME/Meshlink/meshlink"

mkdir -p "\$HOME/.local/share/applications"
cat > "\$HOME/.local/share/applications/meshlink.desktop" << DESKTOP
[Desktop Entry]
Version=1.0
Name=Meshlink
Comment=Decentralized Encrypted Messenger
Exec=xdg-open ${BASE_URL}
Icon=internet-chat
Terminal=false
Type=Application
Categories=Network;InstantMessaging;Chat;
DESKTOP

DESKTOP_DIR=\$(xdg-user-dir DESKTOP 2>/dev/null || echo "\$HOME/Desktop")
if [ -d "\$DESKTOP_DIR" ]; then
    cp "\$HOME/.local/share/applications/meshlink.desktop" "\$DESKTOP_DIR/"
    chmod +x "\$DESKTOP_DIR/meshlink.desktop" 2>/dev/null
    gio set "\$DESKTOP_DIR/meshlink.desktop" metadata::trusted true 2>/dev/null
fi

update-desktop-database "\$HOME/.local/share/applications" 2>/dev/null

echo ""
echo "Done! Shortcut created on Desktop."
echo "Opening Meshlink now..."
echo ""

xdg-open "${BASE_URL}" 2>/dev/null || sensible-browser "${BASE_URL}" 2>/dev/null || echo "Open ${BASE_URL} in your browser"
LINEOF
chmod +x "$SERVER_DIR/nginx/www/installers/meshlink-install.sh"

log "Platform installers generated."

# =============================================================================
# Step 7: Generate server signing key
# =============================================================================
if [ ! -f "$SERVER_DIR/synapse/signing.key" ]; then
    log "Generating server signing key..."
    docker run --rm \
        -v "$SERVER_DIR/synapse:/data" \
        -e SYNAPSE_SERVER_NAME="$SERVER_HOST" \
        -e SYNAPSE_REPORT_STATS=no \
        --entrypoint python3 \
        matrixdotorg/synapse:latest \
        -m synapse.app.homeserver \
        --config-path /data/homeserver.yaml \
        --generate-keys
    log "Signing key generated."
else
    log "Signing key already exists, skipping generation."
fi

# Fix permissions: Synapse runs as UID 991 inside the container
log "Fixing file permissions..."
chmod 644 "$SERVER_DIR/synapse/signing.key"
chmod 644 "$SERVER_DIR/synapse/homeserver.yaml"
chmod 644 "$SERVER_DIR/synapse/log.config"

# Fix synapse_data volume permissions
docker run --rm -v server_synapse_data:/data alpine chown -R 991:991 /data 2>/dev/null || true

# =============================================================================
# Step 8: Build Meshlink UI
# =============================================================================
log "Building Meshlink UI..."
REPO_DIR="$(cd "$SERVER_DIR/.." && pwd)"

# Install Node.js if not available
if ! command -v node &>/dev/null; then
    log "Installing Node.js..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y -qq nodejs
fi

cd "$REPO_DIR"
npm install --production=false 2>/dev/null || npm install
npm run build

# Copy built files to nginx serving directory
mkdir -p "$SERVER_DIR/nginx/www/meshlink"
cp -r "$REPO_DIR/dist/"* "$SERVER_DIR/nginx/www/meshlink/"
log "Meshlink UI built and deployed."

# =============================================================================
# Step 9: Start the stack
# =============================================================================
log "Starting Meshlink server stack..."
cd "$SERVER_DIR"
docker compose pull
docker compose up -d

log "Waiting for server to become healthy (this may take up to 2 minutes)..."
RETRIES=60
HEALTHY=false
while [ $RETRIES -gt 0 ]; do
    if docker compose exec -T synapse python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8008/health')" 2>/dev/null; then
        HEALTHY=true
        break
    fi
    RETRIES=$((RETRIES - 1))
    sleep 3
done

# Ensure nginx is running regardless of healthcheck status
docker compose up -d --no-deps nginx 2>/dev/null || true

if [ "$HEALTHY" = "false" ]; then
    warn "Server is still starting up. It may need a few more seconds."
    warn "Check status with: cd $SERVER_DIR && docker compose ps"
fi

log "Server is running."

# =============================================================================
# Step 9b: Verify external accessibility
# =============================================================================
log "Verifying server is accessible..."

# Check if port 80 is listening
if command -v ss &>/dev/null; then
    if ss -tlnp | grep -q ":80 "; then
        log "Port 80 is listening."
    else
        warn "Port 80 does NOT appear to be listening!"
        warn "Check: docker compose ps nginx"
    fi
fi

# Try to reach the server from localhost
if curl -sf --max-time 5 "http://127.0.0.1/health" >/dev/null 2>&1; then
    log "Server responds on localhost."
else
    warn "Server does not respond on localhost yet. It may still be starting."
fi

# Try to reach via the public IP
if curl -sf --max-time 10 "http://${SERVER_HOST}/health" >/dev/null 2>&1; then
    log "Server responds on ${SERVER_HOST} -- accessible from outside!"
else
    warn "Server does NOT respond on ${SERVER_HOST}."
    warn "Possible causes:"
    warn "  1. Firewall blocking port 80 (check: sudo ufw status / iptables -L)"
    warn "  2. Cloud provider security group not allowing port 80"
    warn "  3. Server is still starting up (wait 1-2 minutes)"
    warn "  4. Wrong IP address (detected: ${SERVER_HOST})"
fi

# =============================================================================
# Step 9: Create admin user
# =============================================================================
log "Creating admin user: @${ADMIN_USER}:${SERVER_HOST}"
docker compose exec -T synapse register_new_matrix_user \
    -u "$ADMIN_USER" \
    -p "$ADMIN_PASSWORD" \
    -a \
    -c /data/homeserver.yaml \
    http://localhost:8008

log "Admin user created."

# =============================================================================
# Step 10: Configure firewall for Docker compatibility
# =============================================================================
log "Configuring firewall..."

if command -v ufw &>/dev/null; then
    # Enable UFW if not active
    ufw --force enable 2>/dev/null || true

    # Add standard port rules
    ufw allow "$HTTP_PORT"/tcp comment "Meshlink HTTP" 2>/dev/null || true
    ufw allow 443/tcp comment "Meshlink HTTPS" 2>/dev/null || true
    ufw allow 3478/tcp comment "Meshlink TURN TCP" 2>/dev/null || true
    ufw allow 3478/udp comment "Meshlink TURN UDP" 2>/dev/null || true
    ufw allow 5349/tcp comment "Meshlink TURN TLS TCP" 2>/dev/null || true
    ufw allow 5349/udp comment "Meshlink TURN TLS UDP" 2>/dev/null || true
    ufw allow 49152:49172/udp comment "Meshlink TURN relay" 2>/dev/null || true

    # Fix Docker + UFW compatibility issue:
    # Docker bypasses UFW by adding iptables rules directly.
    # On systems with UFW policy DROP, external traffic to Docker ports is blocked.
    # This fix adds rules to the DOCKER-USER chain which UFW respects.
    UFW_AFTER="/etc/ufw/after.rules"
    if ! grep -q "MESHLINK-DOCKER-FIX" "$UFW_AFTER" 2>/dev/null; then
        log "Adding Docker+UFW compatibility rules..."
        cat >> "$UFW_AFTER" <<'DOCKERFIX'

# BEGIN MESHLINK-DOCKER-FIX
# Allow external access to Docker-published ports
*filter
:DOCKER-USER - [0:0]
-A DOCKER-USER -p tcp --dport 80 -j ACCEPT
-A DOCKER-USER -p tcp --dport 443 -j ACCEPT
-A DOCKER-USER -p tcp --dport 3478 -j ACCEPT
-A DOCKER-USER -p udp --dport 3478 -j ACCEPT
-A DOCKER-USER -p tcp --dport 5349 -j ACCEPT
-A DOCKER-USER -p udp --dport 5349 -j ACCEPT
-A DOCKER-USER -p udp --dport 49152:49172 -j ACCEPT
-A DOCKER-USER -j RETURN
COMMIT
# END MESHLINK-DOCKER-FIX
DOCKERFIX
        ufw reload
        log "Docker+UFW compatibility rules installed."
    else
        log "Docker+UFW compatibility rules already present."
    fi

    log "Firewall configured."
else
    # No UFW -- add iptables rules directly
    if command -v iptables &>/dev/null; then
        log "Adding iptables ACCEPT rules..."
        iptables -I INPUT -p tcp --dport "$HTTP_PORT" -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p tcp --dport 3478 -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p udp --dport 3478 -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p tcp --dport 5349 -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p udp --dport 5349 -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p udp --dport 49152:49172 -j ACCEPT 2>/dev/null || true
        log "iptables rules added."
    fi
fi

# =============================================================================
# Step 11: Setup weekly auto-cleanup cron job
# =============================================================================
CLEANUP_SCRIPT="$SERVER_DIR/scripts/cleanup.sh"
chmod +x "$CLEANUP_SCRIPT"
CRON_LINE="0 3 * * 0 $CLEANUP_SCRIPT >> /var/log/meshlink-cleanup.log 2>&1"
if ! crontab -l 2>/dev/null | grep -q "meshlink-cleanup"; then
    (crontab -l 2>/dev/null; echo "$CRON_LINE") | crontab -
    log "Weekly cleanup cron job installed (Sundays at 3am)."
else
    log "Cleanup cron job already exists."
fi

# =============================================================================
# Step 12: Setup daily database backup cron job
# =============================================================================
BACKUP_DIR="/var/backups/meshlink"
mkdir -p "$BACKUP_DIR"
BACKUP_CRON="0 2 * * * cd $SERVER_DIR && docker compose exec -T postgres pg_dump -U \${POSTGRES_USER:-synapse} \${POSTGRES_DB:-synapse} | gzip > $BACKUP_DIR/meshlink-db-\$(date +\\%Y\\%m\\%d).sql.gz && find $BACKUP_DIR -name 'meshlink-db-*.sql.gz' -mtime +7 -delete >> /var/log/meshlink-backup.log 2>&1"
if ! crontab -l 2>/dev/null | grep -q "meshlink-db-"; then
    (crontab -l 2>/dev/null; echo "$BACKUP_CRON") | crontab -
    log "Daily database backup cron job installed (2am, keeps 7 days)."
else
    log "Database backup cron job already exists."
fi

# =============================================================================
# Done!
# =============================================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}   Meshlink Server is running!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  Web client:    ${CYAN}${BASE_URL}${NC}"
echo -e "  Admin panel:   ${CYAN}${BASE_URL}/admin${NC}"
echo -e "  Config panel:  ${CYAN}${BASE_URL}/config${NC}"
echo -e "  Admin user:    ${CYAN}@${ADMIN_USER}:${SERVER_HOST}${NC}"
echo ""
echo -e "  Installers:"
echo -e "    Windows:     ${CYAN}${BASE_URL}/installers/Meshlink-Install.bat${NC}"
echo -e "    Linux:       ${CYAN}${BASE_URL}/installers/meshlink-install.sh${NC}"
echo -e "    Android/iOS: ${CYAN}Open ${BASE_URL} in browser -> Add to Home Screen${NC}"
echo ""
echo -e "  Config file:   ${CYAN}${SERVER_DIR}/.env${NC}"
echo -e "  Logs:          ${CYAN}cd ${SERVER_DIR} && docker compose logs -f${NC}"
echo ""
echo -e "  ${YELLOW}IMPORTANT: Save your .env file securely. It contains all secrets.${NC}"
echo ""
