#!/bin/bash
# =============================================================================
# Meshlink Server - Automated Setup Script
# Installs and configures the full Meshlink messaging stack on Ubuntu.
#
# Usage:
#   chmod +x setup.sh && sudo ./setup.sh
#
# What it does:
#   1. Installs Docker and Docker Compose (if missing)
#   2. Generates secure secrets
#   3. Templates all config files with your server parameters
#   4. Starts the full stack (Synapse + Element + PostgreSQL + Coturn + Nginx)
#   5. Creates the first admin user
# =============================================================================

set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[Meshlink]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# --- Pre-flight checks ---
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (use sudo)."
    exit 1
fi

if ! grep -qi 'ubuntu\|debian' /etc/os-release 2>/dev/null; then
    warn "This script is designed for Ubuntu/Debian. Proceeding anyway..."
fi

# --- Determine script and project directories ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

log "Meshlink server directory: $SERVER_DIR"

# =============================================================================
# Step 1: Collect configuration
# =============================================================================
echo ""
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}   Meshlink Server Setup${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# Detect public IP
DETECTED_IP=$(curl -4 -s --max-time 5 ifconfig.co 2>/dev/null || hostname -I | awk '{print $1}')

read -rp "Server IP or domain [$DETECTED_IP]: " SERVER_HOST
SERVER_HOST="${SERVER_HOST:-$DETECTED_IP}"

read -rp "HTTP port [80]: " HTTP_PORT
HTTP_PORT="${HTTP_PORT:-80}"

read -rp "Admin username [admin]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-admin}"

while true; do
    read -rsp "Admin password (min 8 chars): " ADMIN_PASSWORD
    echo ""
    if [ "${#ADMIN_PASSWORD}" -ge 8 ]; then
        break
    fi
    warn "Password must be at least 8 characters."
done

read -rp "Enable open registration? (yes/no) [yes]: " ENABLE_REG
ENABLE_REG="${ENABLE_REG:-yes}"
if [ "$ENABLE_REG" = "yes" ]; then
    ENABLE_REGISTRATION="true"
else
    ENABLE_REGISTRATION="false"
fi

# =============================================================================
# Step 2: Install Docker (if needed)
# =============================================================================
install_docker() {
    if command -v docker &>/dev/null; then
        log "Docker already installed: $(docker --version)"
        return
    fi

    log "Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin

    systemctl enable docker
    systemctl start docker
    log "Docker installed successfully."
}

install_docker

# Ensure docker compose works
if ! docker compose version &>/dev/null; then
    err "docker compose not available. Please install Docker Compose v2."
    exit 1
fi

# =============================================================================
# Step 3: Generate secrets
# =============================================================================
gen_secret() { openssl rand -hex 32; }

POSTGRES_PASSWORD="$(gen_secret)"
REGISTRATION_SHARED_SECRET="$(gen_secret)"
MACAROON_SECRET="$(gen_secret)"
FORM_SECRET="$(gen_secret)"
TURN_SECRET="$(gen_secret)"

log "Secrets generated."

# =============================================================================
# Step 4: Write .env file
# =============================================================================
cat > "$SERVER_DIR/.env" <<EOF
# Meshlink Server Configuration (auto-generated by setup.sh)
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

SERVER_HOST=${SERVER_HOST}
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=443
SYNAPSE_PORT=8008
TURN_PORT=3478
TURN_TLS_PORT=5349
TURN_RELAY_MIN=49152
TURN_RELAY_MAX=49172

SYNAPSE_SERVER_NAME=${SERVER_HOST}
SYNAPSE_REPORT_STATS=no
ENABLE_REGISTRATION=${ENABLE_REGISTRATION}
REGISTRATION_SHARED_SECRET=${REGISTRATION_SHARED_SECRET}

POSTGRES_DB=synapse
POSTGRES_USER=synapse
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

TURN_SECRET=${TURN_SECRET}

ELEMENT_BRAND=Meshlink

ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

chmod 600 "$SERVER_DIR/.env"
log ".env file written."

# =============================================================================
# Step 5: Template config files
# =============================================================================
template_file() {
    local file="$1"
    log "Templating: $file"
    sed -i \
        -e "s|__SERVER_HOST__|${SERVER_HOST}|g" \
        -e "s|__SERVER_NAME__|${SERVER_HOST}|g" \
        -e "s|__POSTGRES_USER__|synapse|g" \
        -e "s|__POSTGRES_PASSWORD__|${POSTGRES_PASSWORD}|g" \
        -e "s|__POSTGRES_DB__|synapse|g" \
        -e "s|__ENABLE_REGISTRATION__|${ENABLE_REGISTRATION}|g" \
        -e "s|__REGISTRATION_SHARED_SECRET__|${REGISTRATION_SHARED_SECRET}|g" \
        -e "s|__MACAROON_SECRET__|${MACAROON_SECRET}|g" \
        -e "s|__FORM_SECRET__|${FORM_SECRET}|g" \
        -e "s|__TURN_SECRET__|${TURN_SECRET}|g" \
        -e "s|__TURN_PORT__|3478|g" \
        "$file"
}

# Copy originals from git before templating (allows re-running setup.sh)
REPO_DIR="$(cd "$SERVER_DIR/.." && pwd)"
if [ -f "$REPO_DIR/.git/HEAD" ]; then
    log "Restoring config templates from git..."
    git -C "$REPO_DIR" checkout -- server/synapse/homeserver.yaml server/coturn/turnserver.conf server/element/config.json 2>/dev/null || true
fi

template_file "$SERVER_DIR/synapse/homeserver.yaml"
template_file "$SERVER_DIR/coturn/turnserver.conf"
template_file "$SERVER_DIR/element/config.json"

log "All config files templated."

# =============================================================================
# Step 6: Create directories for nginx static files (installers)
# =============================================================================
mkdir -p "$SERVER_DIR/nginx/www/installers"

# Generate platform installers pointing to this server
BASE_URL="http://${SERVER_HOST}"
if [ "$HTTP_PORT" != "80" ]; then
    BASE_URL="http://${SERVER_HOST}:${HTTP_PORT}"
fi

# Windows installer
cat > "$SERVER_DIR/nginx/www/installers/Meshlink-Install.bat" <<WINEOF
@echo off
title Meshlink Installer
color 0A
echo.
echo  ========================================
echo     Meshlink - Decentralized Messenger
echo  ========================================
echo.
echo  Installing Meshlink...

set "SERVER_URL=${BASE_URL}"

mkdir "%USERPROFILE%\Meshlink" 2>nul

echo @echo off > "%USERPROFILE%\Meshlink\Meshlink.bat"
echo start "" "%SERVER_URL%" >> "%USERPROFILE%\Meshlink\Meshlink.bat"

echo Set ws = CreateObject("WScript.Shell") > "%TEMP%\ml_sc.vbs"
echo Set sc = ws.CreateShortcut(ws.SpecialFolders("Desktop") ^& "\Meshlink.lnk") >> "%TEMP%\ml_sc.vbs"
echo sc.TargetPath = "%USERPROFILE%\Meshlink\Meshlink.bat" >> "%TEMP%\ml_sc.vbs"
echo sc.IconLocation = "shell32.dll,14" >> "%TEMP%\ml_sc.vbs"
echo sc.Description = "Meshlink Messenger" >> "%TEMP%\ml_sc.vbs"
echo sc.WindowStyle = 7 >> "%TEMP%\ml_sc.vbs"
echo sc.Save >> "%TEMP%\ml_sc.vbs"
cscript //nologo "%TEMP%\ml_sc.vbs"
del "%TEMP%\ml_sc.vbs" 2>nul

mkdir "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Meshlink" 2>nul
echo Set ws = CreateObject("WScript.Shell") > "%TEMP%\ml_sm.vbs"
echo Set sc = ws.CreateShortcut("%APPDATA%\Microsoft\Windows\Start Menu\Programs\Meshlink\Meshlink.lnk") >> "%TEMP%\ml_sm.vbs"
echo sc.TargetPath = "%USERPROFILE%\Meshlink\Meshlink.bat" >> "%TEMP%\ml_sm.vbs"
echo sc.IconLocation = "shell32.dll,14" >> "%TEMP%\ml_sm.vbs"
echo sc.Description = "Meshlink Messenger" >> "%TEMP%\ml_sm.vbs"
echo sc.Save >> "%TEMP%\ml_sm.vbs"
cscript //nologo "%TEMP%\ml_sm.vbs"
del "%TEMP%\ml_sm.vbs" 2>nul

echo.
echo  ========================================
echo   Done! Shortcut created on Desktop.
echo   Opening Meshlink now...
echo  ========================================

start "" "%SERVER_URL%"
exit
WINEOF

# Linux installer
cat > "$SERVER_DIR/nginx/www/installers/meshlink-install.sh" <<LINEOF
#!/bin/bash
# Meshlink Installer for Linux

SERVER_URL="${BASE_URL}"

echo ""
echo "========================================"
echo "   Meshlink - Decentralized Messenger"
echo "========================================"
echo ""
echo "Installing..."

mkdir -p "\$HOME/Meshlink"

cat > "\$HOME/Meshlink/meshlink" << 'LAUNCHER'
#!/bin/bash
xdg-open "${BASE_URL}" 2>/dev/null || sensible-browser "${BASE_URL}" 2>/dev/null || firefox "${BASE_URL}" 2>/dev/null || google-chrome "${BASE_URL}" 2>/dev/null
LAUNCHER
chmod +x "\$HOME/Meshlink/meshlink"

mkdir -p "\$HOME/.local/share/applications"
cat > "\$HOME/.local/share/applications/meshlink.desktop" << DESKTOP
[Desktop Entry]
Version=1.0
Name=Meshlink
Comment=Decentralized Encrypted Messenger
Exec=xdg-open ${BASE_URL}
Icon=internet-chat
Terminal=false
Type=Application
Categories=Network;InstantMessaging;Chat;
DESKTOP

DESKTOP_DIR=\$(xdg-user-dir DESKTOP 2>/dev/null || echo "\$HOME/Desktop")
if [ -d "\$DESKTOP_DIR" ]; then
    cp "\$HOME/.local/share/applications/meshlink.desktop" "\$DESKTOP_DIR/"
    chmod +x "\$DESKTOP_DIR/meshlink.desktop" 2>/dev/null
    gio set "\$DESKTOP_DIR/meshlink.desktop" metadata::trusted true 2>/dev/null
fi

update-desktop-database "\$HOME/.local/share/applications" 2>/dev/null

echo ""
echo "Done! Shortcut created on Desktop."
echo "Opening Meshlink now..."
echo ""

xdg-open "${BASE_URL}" 2>/dev/null || sensible-browser "${BASE_URL}" 2>/dev/null || echo "Open ${BASE_URL} in your browser"
LINEOF
chmod +x "$SERVER_DIR/nginx/www/installers/meshlink-install.sh"

log "Platform installers generated."

# =============================================================================
# Step 7: Generate Synapse signing key
# =============================================================================
if [ ! -f "$SERVER_DIR/synapse/signing.key" ]; then
    log "Generating Synapse signing key..."
    docker run --rm \
        -v "$SERVER_DIR/synapse:/data" \
        -e SYNAPSE_SERVER_NAME="$SERVER_HOST" \
        -e SYNAPSE_REPORT_STATS=no \
        --entrypoint python3 \
        matrixdotorg/synapse:latest \
        -m synapse.app.homeserver \
        --config-path /data/homeserver.yaml \
        --generate-keys
    log "Signing key generated."
else
    log "Signing key already exists, skipping generation."
fi

# Fix permissions: Synapse runs as UID 991 inside the container
log "Fixing file permissions..."
chmod 644 "$SERVER_DIR/synapse/signing.key"
chmod 644 "$SERVER_DIR/synapse/homeserver.yaml"
chmod 644 "$SERVER_DIR/synapse/log.config"

# Fix synapse_data volume permissions
docker run --rm -v server_synapse_data:/data alpine chown -R 991:991 /data 2>/dev/null || true

# =============================================================================
# Step 8: Start the stack
# =============================================================================
log "Starting Meshlink server stack..."
cd "$SERVER_DIR"
docker compose pull
docker compose up -d

log "Waiting for Synapse to become healthy..."
RETRIES=30
while [ $RETRIES -gt 0 ]; do
    if docker compose exec -T synapse wget -qO /dev/null http://localhost:8008/health 2>/dev/null; then
        break
    fi
    RETRIES=$((RETRIES - 1))
    sleep 5
done

if [ $RETRIES -eq 0 ]; then
    err "Synapse did not become healthy in time. Check logs: docker compose logs synapse"
    exit 1
fi

log "Synapse is healthy."

# =============================================================================
# Step 9: Create admin user
# =============================================================================
log "Creating admin user: @${ADMIN_USER}:${SERVER_HOST}"
docker compose exec -T synapse register_new_matrix_user \
    -u "$ADMIN_USER" \
    -p "$ADMIN_PASSWORD" \
    -a \
    -c /data/homeserver.yaml \
    http://localhost:8008

log "Admin user created."

# =============================================================================
# Step 10: Configure firewall (if ufw is active)
# =============================================================================
if command -v ufw &>/dev/null && ufw status | grep -q "active"; then
    log "Configuring firewall (ufw)..."
    ufw allow "$HTTP_PORT"/tcp comment "Meshlink HTTP"
    ufw allow 3478/tcp comment "Meshlink TURN TCP"
    ufw allow 3478/udp comment "Meshlink TURN UDP"
    ufw allow 5349/tcp comment "Meshlink TURN TLS TCP"
    ufw allow 5349/udp comment "Meshlink TURN TLS UDP"
    ufw allow 49152:49172/udp comment "Meshlink TURN relay"
    log "Firewall rules added."
fi

# =============================================================================
# Done!
# =============================================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}   Meshlink Server is running!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  Web client:    ${CYAN}${BASE_URL}${NC}"
echo -e "  Admin panel:   ${CYAN}${BASE_URL}/admin${NC}"
echo -e "  Admin user:    ${CYAN}@${ADMIN_USER}:${SERVER_HOST}${NC}"
echo ""
echo -e "  Installers:"
echo -e "    Windows:     ${CYAN}${BASE_URL}/installers/Meshlink-Install.bat${NC}"
echo -e "    Linux:       ${CYAN}${BASE_URL}/installers/meshlink-install.sh${NC}"
echo -e "    Android/iOS: ${CYAN}Open ${BASE_URL} in browser -> Add to Home Screen${NC}"
echo ""
echo -e "  Config file:   ${CYAN}${SERVER_DIR}/.env${NC}"
echo -e "  Logs:          ${CYAN}cd ${SERVER_DIR} && docker compose logs -f${NC}"
echo ""
echo -e "  ${YELLOW}IMPORTANT: Save your .env file securely. It contains all secrets.${NC}"
echo ""
